import type { CategoryBreakdown, FinanceSummary, PaymentMethodBreakdown, SpendingInsight, SpendingPoint } from '@/types'

export const mockFinanceSummary: FinanceSummary = {
  currentBalance: 124560,
  totalIncome: 185000,
  totalExpense: 60440,
  udhaarReceivable: 18500,
  balanceTrend: 4.5,
  incomeTrend: 6.2,
  expenseTrend: -8,
  udhaarTrend: 2.1,
}

export const mockWeeklySpending: SpendingPoint[] = [
  { label: 'Mon', income: 0, expense: 1840, date: '2026-09-16' },
  { label: 'Tue', income: 0, expense: 2650, date: '2026-09-17' },
  { label: 'Wed', income: 22000, expense: 980, date: '2026-09-18' },
  { label: 'Thu', income: 0, expense: 4200, date: '2026-09-19' },
  { label: 'Fri', income: 0, expense: 1560, date: '2026-09-20' },
  { label: 'Sat', income: 0, expense: 3850, date: '2026-09-21' },
  { label: 'Sun', income: 0, expense: 2850, date: '2026-09-22' },
]

export const mockMonthlySpending: SpendingPoint[] = [
  { label: 'Mar', income: 152000, expense: 58200, date: '2026-03-01' },
  { label: 'Apr', income: 152000, expense: 61400, date: '2026-04-01' },
  { label: 'May', income: 158000, expense: 54900, date: '2026-05-01' },
  { label: 'Jun', income: 158000, expense: 66800, date: '2026-06-01' },
  { label: 'Jul', income: 163000, expense: 59200, date: '2026-07-01' },
  { label: 'Aug', income: 167296, expense: 65700, date: '2026-08-01' },
  { label: 'Sep', income: 185000, expense: 60440, date: '2026-09-01' },
]

export const mockCategoryBreakdown: CategoryBreakdown[] = [
  { category: 'food', label: 'Food', amount: 18400, color: 'var(--color-danger)' },
  { category: 'shopping', label: 'Shopping', amount: 12600, color: 'var(--color-pink)' },
  { category: 'bills', label: 'Bills', amount: 9840, color: 'var(--color-warning)' },
  { category: 'transport', label: 'Transport', amount: 7200, color: 'var(--color-info)' },
  { category: 'health', label: 'Health', amount: 4600, color: 'var(--color-green)' },
  { category: 'other', label: 'Other', amount: 4600, color: 'var(--color-ink-muted)' },
  { category: 'entertainment', label: 'Entertainment', amount: 3200, color: 'var(--color-cyan)' },
]

export const mockPaymentMethods: PaymentMethodBreakdown[] = [
  { method: 'UPI', amount: 27198, percentage: 45 },
  { method: 'Card', amount: 18132, percentage: 30 },
  { method: 'Bank Transfer', amount: 9066, percentage: 15 },
  { method: 'Cash', amount: 4231, percentage: 7 },
  { method: 'Net Banking', amount: 1813, percentage: 3 },
]

export const mockSpendingInsight: SpendingInsight = {
  headline: 'You spent 8% less than last month',
  detail: 'Mock insight — will be generated by your AI assistant in a future phase.',
  trendPoints: [64200, 61400, 66800, 59200, 65700, 60440],
  isMock: true,
}
